Numpy tutorial

In [4]:
import numpy as np


numpy is short for numerical python. it is used for heavy and fast mathematical operations.

In [5]:
a= np.array([1,2,3,4])
print(a)
print(a.shape)


[1 2 3 4]
(4,)


In [6]:
b= np.array([(1,2,3,4), (5,6,7,8), (9,10,11,12)])
print(b)
print(b.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


initialising placeholders in numpy array

In [9]:
x= np.full((3,5), 69)
print(x)

[[69 69 69 69 69]
 [69 69 69 69 69]
 [69 69 69 69 69]]


In [10]:
i= np.eye(5, dtype=int)
print(i)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [11]:
i= np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


creating an array with random values

In [14]:
a= np.random.random((3,3))
print(a)


[[0.10216129 0.66423282 0.42647157]
 [0.57711835 0.36245862 0.0651422 ]
 [0.59063918 0.40043287 0.93343159]]


In [16]:
b= np.random.randint(10,100,(3,3))
print(b)

[[35 94 38]
 [40 34 12]
 [56 75 23]]


In [17]:
print(b.size)

9


Mathematical operations on a numpy array

In [19]:
a= np.random.randint(0,10,(3,4))
b= np.random.randint(10,20,(3,4))
print(a)
print(b)
print(a*b)

[[2 7 1 1]
 [0 4 1 4]
 [9 8 3 6]]
[[15 14 14 17]
 [13 16 11 13]
 [10 14 16 16]]
[[ 30  98  14  17]
 [  0  64  11  52]
 [ 90 112  48  96]]


In [20]:
print(np.add(a,b))

[[17 21 15 18]
 [13 20 12 17]
 [19 22 19 22]]
